imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    tests:
        override:
            -
                command: 'make phpunit'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
